-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcI/Iuq//7yJRfQ0a
6vfz3Uk3Z5PhIaJAhn0iRydDKHKgCgYIKoZIzj0DAQehRANCAAStrHoBm8FAcabO
fc4sG6S5NxtDbDjW2sxzgiQbxojPVTEicZtjO6wLzDw83QyeH/5ddYUV1fsTAeEx
u5xuTa3r
-----END PRIVATE KEY-----