// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM5bntd2bkquc_IMCB2G4tTz0cL6BrZUg',
    appId: '1:60189244962:web:1e0c18b0133e49f638547b',
    messagingSenderId: '60189244962',
    projectId: 'genghis-khan-restaurant',
    authDomain: 'genghis-khan-restaurant.firebaseapp.com',
    storageBucket: 'genghis-khan-restaurant.firebasestorage.app',
    measurementId: 'G-BXVJE5Z320',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8pJIVEGIFvGs2q75fRgE08mTL4Tr7pU',
    appId: '1:60189244962:android:12f6c9ce4913b56038547b',
    messagingSenderId: '60189244962',
    projectId: 'genghis-khan-restaurant',
    storageBucket: 'genghis-khan-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7sfy7W77_zqx6gwziP_Sc07sq2rT33Q',
    appId: '1:60189244962:ios:2a3d7f9dc089cc3438547b',
    messagingSenderId: '60189244962',
    projectId: 'genghis-khan-restaurant',
    storageBucket: 'genghis-khan-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.gzresturent',
  );
}
